### ISSUE TITLE
HTML export issue in Mode

### ISSUE THREAD

**Issue by KleinK0910** [vizzuhq/ipyvizzu-story#26]
HTML export - story.export_to_html(" ") - does not work like in other notebooks, there's no output file generated.

**Comment by veghdev** [comment]
@KleinK0910 @petervidos I'm not familiar with Mode. I searched for it but couldn't find a solution to access the Mode's filesystem in the GUI.

However, the command "story.export_to_html()" works, but as I can see, Mode does not give graphical access to the created file.

A solution could be, for example:
```python
print(story.to_html())
```

It writes the html content as a string to the notebook output, but you have to copy and paste it into an empty .html file.
