### ISSUE TITLE
Colab issues

### ISSUE THREAD

**Issue by petervidos** [vizzuhq/ipyvizzu-story#3]
- [x] The chart appears but its horizontal and vertical size are both too big by default. -> added Story.set_size(width, height) method in 0.2.0 (for example: story.set_size("800px", "480px"))
- [ ] PgUp, PgDn buttons scroll the notebook even after the chart is clicked #42 
- [x] Full screen button has no effect -> disabled in Colab, but there is a built-in view output fullscreen option

**Comment by veghdev** [comment]
separated into #42
