### ISSUE TITLE
python and js development: support anim options

### ISSUE THREAD

**Issue by rakshasha-medhi** [vizzuhq/ipyvizzu-story#52]
I'm trying to redo this example from ipyvizzu and get it working in ipyvizzu-story:
https://ipyvizzu.vizzuhq.com/examples/stories/musicformats/musicformats.html

I'm interested with this model because it looks to be the most complex out of all the examples available in vizzuhq website.

However in the first block of code, I encountered error:
NotImplementedError: Anim options are not supported.

the error came from these lines of code which I modify in order to make it work with ipyvizzu-story:
```
for year in range(1973, 2021):
    config["title"] = f"Music Revenue by Format - Year by Year {year}"
    slide1 = Slide(Step(
        Data.filter(f"parseInt(record.Year) == {year}"),
        Config(config),
        # duration=0.2,
        # x={"easing": "linear", "delay": 0},
        # y={"delay": 0},
        # show={"delay": 0},
        # hide={"delay": 0},
        # title={"duration": 0, "delay": 0},
    )
    )

    story.add_slide(slide1)

story.add_slide(slide1)
story.export_to_html('musicformats.html')
```

Those I comment-out were the lines that causing the error.
Without them I was able to export to html.

So is it possible to remake all the examples from ipyvizzu in ipyvizzu-story?
Or are there limitations in ipyvizzu-story library in terms of features compared to the ipyvizzu?

**Comment by veghdev** [comment]
Hi, anim options are currently not supported in ipyvizzu-story. We are working on it and probably publish the solution in one of the next releases.

**Comment by veghdev** [comment]
@rakshasha-medhi Hi, Anim options support will be in version 0.7.0 just in a few days.
